version: '3.8'

services:
  database:
    image: postgres:15.0
    container_name: barbearia-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - barbearia-network

  backend:
    build: 
      context: ./apps/backend
      dockerfile: Dockerfile
    container_name: barbearia-backend
    restart: always
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "8080:8080"
    networks:
      - barbearia-network

  bot:
    build: ./apps/bot
    container_name: barbearia-bot
    restart: always
    depends_on:
      - database
    environment:
      DATABASE_URL: ${DATABASE_URL}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
    volumes:
      - ./apps/bot:/app
    networks:
      - barbearia-network

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    container_name: barbearia-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:5173"
    networks:
      - barbearia-network

volumes:
  pgdata:

networks:
  barbearia-network:
    driver: bridge
