server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://database:5432/barbearia
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true